/// Flutter icons Knitting
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Knitting
///      fonts:
///       - asset: fonts/Knitting.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Knitting {
  Knitting._();

  static const _kFontFam = 'Knitting';
  static const String? _kFontPkg = null;

  static const IconData clear = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purl = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
