/// Flutter icons Knitting
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Knitting
///      fonts:
///       - asset: fonts/Knitting.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Knitting {
  Knitting._();

  static const _kFontFam = 'Knitting';
  static const String? _kFontPkg = null;

  static const IconData k2tog = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k3tog = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nostitch = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ktbl = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p2tog = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purl = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p3tog = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ssp = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yarnover = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ssk = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
